apiVersion: v1
kind: ConfigMap
metadata:
  name: delta-demo-frontend-initial
  namespace: delta
data:
  initial.js: |
    (function (window) {
      if (window.__INITIAL_CONFIG__) {
        return;
      }
      // eslint-disable-next-line no-var
      var __INITIAL_CONFIG__ = {
        APP_CUSTOMER: "capitaland",
        APP_ENDPOINT: "//delta.wzxmt.com",
        API_ENDPOINT: "http://delta-services.wzxmt.com",
        API_MIXBUDGET: "http://delta-services.wzxmt.com/mixbudget",
        API_MIXBUDGET_HOSTV1: "http://delta-services.wzxmt.com/mixbudget/api/1021/v1",
        API_MIXBUDGET_HOSTV2: "http://delta-services.wzxmt.com/mixbudget/api/v2",
        DASHBOARD_ADDRESS: "delta.wzxmt.com/",
        DEPOPT05: true,
        PRODUCT: "retail",
      };
      window.__INITIAL_CONFIG__ = __INITIAL_CONFIG__;
    })(this);
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: delta-demo-amss-frontend
  namespace: delta
  labels: 
    name: delta-demo-frontend
    app: amss
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: delta-demo-frontend
      app: amss
  template:
    metadata:
      labels: 
        app: amss
        name: delta-demo-frontend
    spec:
      containers:
      - name: delta-demo-amss-frontend
        image: bridge5/kaide-frontend:nightly
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: delta-demo-frontend-initial       
          mountPath: /var/www/main/initial.js
          subPath: initial.js
      volumes:    
        - name: delta-demo-frontend-initial      
          configMap:        
            name: delta-demo-frontend-initial
      imagePullSecrets:
      - name: harborlogin
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: 
        runAsUser: 0
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 7
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata: 
  name: delta-demo-amss-frontend
  namespace: delta
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector: 
    name: delta-demo-frontend
    app: amss
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: delta-demo-amss-frontend
  namespace: delta
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`delta.wzxmt.com`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: delta-demo-amss-frontend
      port: 80
